# Generated by Django 4.2 on 2023-04-29 12:16

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acabamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acabamento', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Acabamento',
                'verbose_name_plural': 'Acabamentos',
                'ordering': ['acabamento'],
            },
        ),
        migrations.CreateModel(
            name='ModeloDivisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Modelo Divisor',
                'verbose_name_plural': 'Modelo Divisores',
            },
        ),
        migrations.CreateModel(
            name='ModeloDivisoriaAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Modelo Divisoria Ambiente',
                'verbose_name_plural': 'Modelos Divisorias Ambiente',
            },
        ),
        migrations.CreateModel(
            name='ModeloPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Modelo Perfil',
                'verbose_name_plural': 'Modelo Perfis',
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='ModeloPerfilPuxador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Modelo Perfil Puxador',
                'verbose_name_plural': 'Modelo Perfis Puxadores',
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='ModeloPuxador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Modelo Puxador',
                'verbose_name_plural': 'Modelo Puxadores',
            },
        ),
        migrations.CreateModel(
            name='ModeloVidro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Modelo Vidro',
                'verbose_name_plural': 'Modelos Vidros',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPuxador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.acabamento')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.modeloperfilpuxador')),
                ('perfilencaixe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.modeloperfil')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipo')),
            ],
            options={
                'verbose_name': 'Perfil Puxador',
                'verbose_name_plural': 'Perfis Puxadores',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('encaixe', models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], max_length=3, verbose_name='Permite encaixe de Perfil Puxador?')),
                ('puxadorsobreposto', models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], max_length=3, verbose_name='Permite encaixe de Puxador Sobreposto?')),
                ('testando', multiselectfield.db.fields.MultiSelectField(choices=[('nao possui', 'Não possui'), ('Vinte', '2020'), ('trinta', '3030'), ('Quarenta', '4040'), ('Cinquenta', '5050'), ('Sessenta', '6060'), ('Setenta', '7070')], max_length=50)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.acabamento')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.modeloperfil')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipo')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['descricao'],
            },
        ),
    ]
