# Generated by Django 4.2 on 2023-04-29 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_perfilpuxador_perfilencaixe_puxador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelodivisor',
            options={'ordering': ['modelo'], 'verbose_name': 'Modelo Divisor', 'verbose_name_plural': 'Modelo Divisores'},
        ),
        migrations.AlterModelOptions(
            name='modelodivisoriaambiente',
            options={'ordering': ['modelo'], 'verbose_name': 'Modelo Divisoria Ambiente', 'verbose_name_plural': 'Modelos Divisorias Ambiente'},
        ),
        migrations.AlterModelOptions(
            name='modelopuxador',
            options={'ordering': ['modelo'], 'verbose_name': 'Modelo Puxador', 'verbose_name_plural': 'Modelo Puxadores'},
        ),
        migrations.AlterModelOptions(
            name='modelovidro',
            options={'ordering': ['modelo'], 'verbose_name': 'Modelo Vidro', 'verbose_name_plural': 'Modelos Vidros'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['tipo']},
        ),
        migrations.CreateModel(
            name='Vidro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.modelovidro')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipo')),
            ],
            options={
                'verbose_name': 'Vidro',
                'verbose_name_plural': 'Vidros',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='DivisoriaAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('linha', models.CharField(choices=[('Doppio', 'Doppio'), ('mil', '1000')], max_length=50)),
                ('posicao', models.CharField(choices=[('Travessa/Inferior', 'Travessa/Inferior'), ('Superior', 'Superior'), ('Lateral', 'Lateral'), ('Superior/Inferior', 'Superior/Inferior'), ('Inferior', 'Inferior'), ('Travessa', 'Travessa')], max_length=50)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.acabamento')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.modelodivisoriaambiente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipo')),
            ],
            options={
                'verbose_name': 'Divisor',
                'verbose_name_plural': 'Divisores',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Divisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.acabamento')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.modelodivisor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipo')),
            ],
            options={
                'verbose_name': 'Divisor',
                'verbose_name_plural': 'Divisores',
                'ordering': ['descricao'],
            },
        ),
    ]
