# Generated by Django 4.2 on 2023-06-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_perfil_divisor_perfil_encaixedivisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='perfil_puxador',
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_puxador',
            field=models.ManyToManyField(blank=True, to='cadastros.perfilpuxador', verbose_name='Perfil Puxador'),
        ),
    ]
