# Generated by Django 4.2 on 2023-06-19 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_perfil_perfil_puxador_perfil_perfil_puxador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='puxadorsobreposto',
        ),
        migrations.AddField(
            model_name='perfil',
            name='puxador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.puxador', verbose_name='Puxador'),
        ),
    ]
