# Generated by Django 4.2 on 2023-05-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_modelodivisor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisor',
            options={'ordering': ['descricao'], 'verbose_name': 'Perfil Divisor', 'verbose_name_plural': 'Perfis Divisores'},
        ),
        migrations.AlterModelOptions(
            name='divisoriaambiente',
            options={'ordering': ['descricao'], 'verbose_name': 'Perfil Divisoria Ambiente', 'verbose_name_plural': 'Perfis Divisorias Ambiente'},
        ),
    ]
