# Generated by Django 4.2 on 2023-05-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_divisor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilpuxador',
            name='perfilencaixe',
        ),
    ]
