# Generated by Django 4.2 on 2023-06-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_remove_perfil_puxadorsobreposto_perfil_puxador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='divisor',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='puxador',
        ),
        migrations.AddField(
            model_name='perfil',
            name='divisor',
            field=models.ManyToManyField(blank=True, to='cadastros.divisor', verbose_name='Divisor'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='puxador',
            field=models.ManyToManyField(blank=True, to='cadastros.puxador', verbose_name='Puxador'),
        ),
    ]
