# Generated by Django 4.2 on 2023-06-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_perfil_divisor_remove_perfil_puxador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisor',
            name='codigo',
            field=models.CharField(max_length=6, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='divisoriaambiente',
            name='codigo',
            field=models.CharField(max_length=6, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='codigo',
            field=models.CharField(max_length=6, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='codigo',
            field=models.CharField(max_length=6, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='vidro',
            name='codigo',
            field=models.CharField(max_length=6, unique=True, verbose_name='Código'),
        ),
    ]
