# Generated by Django 4.2 on 2023-05-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_perfilpuxador_perfilencaixe'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='encaixeperfilpuxador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.perfilpuxador'),
            preserve_default=False,
        ),
    ]
