# Generated by Django 4.2 on 2023-05-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_perfil_encaixeperfilpuxador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='encaixeperfilpuxador',
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_puxador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.perfilpuxador', verbose_name='Perfil Puxador'),
            preserve_default=False,
        ),
    ]
