# Generated by Django 4.2 on 2023-05-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_remove_perfil_encaixeperfilpuxador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='testando',
        ),
        migrations.AddField(
            model_name='perfil',
            name='encaixepuxador',
            field=models.BooleanField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], default=1, max_length=3, verbose_name='Permite encaixe de Puxador?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='encaixe',
            field=models.BooleanField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], max_length=3, verbose_name='Permite encaixe de Perfil Puxador?'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puxadorsobreposto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.puxador', verbose_name='Puxador'),
        ),
    ]
