# Generated by Django 4.2 on 2023-05-15 17:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_remove_perfil_testando_perfil_encaixepuxador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='puxadorsobreposto',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=15),
        ),
    ]
