# Generated by Django 4.2 on 2023-07-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_divisoriaambiente_linha'),
    ]

    operations = [
        migrations.AddField(
            model_name='acabamento',
            name='codigo_rgb',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
