# Generated by Django 4.2 on 2023-05-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_perfil_puxadorsobreposto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='puxadorsobreposto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.puxador', verbose_name='Puxadores'),
        ),
    ]
