# Generated by Django 4.2 on 2023-07-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_acabamento_codigo_rgb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acabamento',
            name='codigo_rgb',
            field=models.CharField(max_length=15, verbose_name='Código RGB'),
        ),
    ]
