# Generated by Django 4.2 on 2023-05-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_perfil_puxadorsobreposto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='encaixe',
            field=models.BooleanField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], default='Nao', max_length=5),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='encaixepuxador',
            field=models.BooleanField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], default='Nao', max_length=3),
        ),
    ]
