# Generated by Django 4.2 on 2023-05-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_alter_perfil_encaixe_alter_perfil_encaixepuxador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='encaixe',
            field=models.CharField(choices=[('True', 'Sim'), ('False', 'Não')], default='Não', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='encaixepuxador',
            field=models.CharField(choices=[('True', 'Sim'), ('False', 'Não')], default='Não', max_length=10),
        ),
    ]
