# Generated by Django 4.2 on 2023-05-16 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=8)),
                ('data_pedido', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 16, 16, 44, 20, 941741))),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('C', 'Cancelado'), ('F', 'Finalizado'), ('P', 'Produção')], default='Aberto', max_length=10)),
                ('quantidade', models.CharField(max_length=2)),
                ('largura', models.CharField(max_length=4)),
                ('altura', models.CharField(max_length=4)),
                ('abertura', models.CharField(choices=[('D', 'Direita'), ('E', 'Esquerda'), ('C', 'Cima'), ('B', 'Baixo')], max_length=10)),
                ('linha', models.CharField(choices=[('Doppio', 'Doppio'), ('mil', '1000')], max_length=10, verbose_name='Linha')),
                ('acabamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.acabamento')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.cliente')),
                ('divisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.divisor', verbose_name='Divisor')),
                ('divisoriaambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.divisoriaambiente', verbose_name='Divisoria de Ambiente')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.perfil', verbose_name='Perfil')),
                ('perfilpuxador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.perfilpuxador', verbose_name='Perfil Puxador')),
                ('puxador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.puxador', verbose_name='Puxador')),
                ('vidro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.vidro', verbose_name='Vidro')),
            ],
        ),
    ]
