# Generated by Django 4.2 on 2023-06-19 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0007_alter_pedido_data_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 19, 10, 42, 16, 712357)),
        ),
    ]
