# Generated by Django 4.2 on 2023-07-03 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0016_alter_pedido_acabamento_alter_pedido_data_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='abertura',
            field=models.CharField(choices=[('D', 'Direita'), ('E', 'Esquerda'), ('C', 'Cima'), ('B', 'Baixo')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 10, 19, 51, 60012)),
        ),
    ]
