# Generated by Django 4.2 on 2023-07-13 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0019_alter_pedido_data_pedido_alter_pedido_linha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 14, 5, 16, 924086)),
        ),
    ]
