# Generated by Django 4.2 on 2023-07-26 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0021_alter_pedido_data_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='altura',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 15, 44, 31, 588690)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='largura',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
