# Generated by Django 4.2 on 2023-07-26 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0022_alter_pedido_altura_alter_pedido_data_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='altura',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 15, 55, 6, 915706)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='largura',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
