# Generated by Django 4.2 on 2023-07-26 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0024_alter_pedido_altura_alter_pedido_data_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 16, 19, 8, 816353)),
        ),
    ]
