# Generated by Django 4.2 on 2023-05-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Descrição')),
                ('cpf_cnpj', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=150, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=6, verbose_name='Número')),
                ('bairro', models.CharField(max_length=150, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=150, verbose_name='Cidade')),
                ('Telefone', models.CharField(max_length=9, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
