# Generated by Django 4.2 on 2023-05-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_cliente_telefone_alter_cliente_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Telefone',
            new_name='telefone',
        ),
    ]
